### ISSUE TITLE
Request new module: CP4S

### ISSUE THREAD

**Issue by SaloniRathi** [cloud-native-toolkit/automation-modules#158]
**Related user story**
I have created a script for cp4s installation on ocp

**Type of module**
gitops 

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
CP4S installation on ocp 

**What is the category of the module?**
Software Infrastructure

**Comment by seansund** [comment]
@SaloniRathi Does this script install all of Cloud Pak for Security on a cluster? Our strategy is to "un-pack" the components of the cloud paks and instead of having one module to install the entire cloud pak, we have individual modules to install the individual software components. Provide a listing of the software components in CP4S and we can create individual modules for each of them.

**Comment by addanuj** [comment]
@seansund  our contribution here is to provide a module that automates the deployment of CP4S on any cloud, with an assumption that required hardware and OCP cluster have already been set up and running. 
In other words, we are contributing a module at the 4xx (Applications) layer of software everywhere.
CP4S is a single application that cannot be further broken into individual components, 
refer to the link https://cloud.ibm.com/docs/cloud-pak-security -> we are trying to automate steps 2 & 3 here.

Please let us know if you need any more information.
 @mjperrins @triceam @beshanb1

**Comment by diimallya** [comment]
@seansund 
As per the documentation of CP4S installation, it is all about deploying a single operator and an instance of that. Ref: https://www.ibm.com/docs/en/cloud-paks/cp-security/1.9?topic=installing-cloud-pak-security-by-using-openshift-web-console. 
Hence planning to implement in single gitops module. Could you please change the type of this module request to gitops and approve the same so that I can start working it. Or please let me if I need to create another issue, requesting for a gitops template module.
Thanks,
Divya.
